# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
cache: packages

env:
  - GCAMDATA_USE_JAVA=TRUE

r_github_packages:
  - jimhester/covr
  - krlmlr/mockr

script:
  - R CMD build .
  - travis_wait R CMD check *.tar.gz

after_success:
  - travis_wait Rscript coverage.R
